# Configuration for a plugin published to npm
[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="reports/accueil.html"
    path = "" 

    [[plugins.inputs.audits]]
    output_path="reports/fr/index.html"
    path = "/fr/index.html"

    [[plugins.inputs.audits]]
    output_path="reports/fr/artistes.html"
    path = "/fr/artistes.html"  

    [[plugins.inputs.audits]]
    output_path="reports/fr/david_lynch.html"
    path = "/fr/david_lynch.html" 

    [[plugins.inputs.audits]]
    output_path="reports/fr/untitled.html"
    path = "/fr/untitled.html"  

    [[plugins.inputs.audits]]
    output_path="reports/fr/contact.html"
    path = "/fr/contact.html"

    [[plugins.inputs.audits]]
    output_path="reports/404.html"
    path = "404.html"

 