# Configuration for a plugin published to npm
[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="reports/accueil.html"
    path = "" #la racine du site

    [[plugins.inputs.audits]]
    output_path="reports/fr/index.html"
    path = "" #la racine du site

 